const AppStrings = {
    
    TOKEN: 'token',
    USER_ID: 'user_id',
    USER_TYPE:'user_type',
    PROPERTY_ID:'Property_id',
    ROLE: 'role',
    FIRST_NAME: 'first_name',
    LAST_NAME: 'last_name',
    EMAIL: 'user_email_id',
    HW_EMAIL: 'hw_email_id',
    PHONE: 'contact_no',
    PROFILE: 'image',
    APP_TYPE: 'Customer',
    DEVICE_TOKEN: 'deviceToken',
    NOTI_COUNT: 'notiCount',
    DATE:'date',
    TIME:'time',
    STATUS:'status',
    CREATED_BY:'created_by',
    API_KEY:'api_key',
    token: 'token',
    PRIORITY:'priority',
    deviceToken: 'deviceToken',

    something_went_wrong: "Something went wrong. Please try again later!",
    required: "Email Address is Required",
    pass_required: "Password is required.",
    invalid_email: "Please enter valid email address.",
    invalid_password: "PASSWORD should be greater than 6 characters.",
    invalid_confirm_password: "CONFIRM PASSWORD is not matching to password.",
    PLEASE_ENTER_VALID_PASS: "Invalid Password",
    email_required:'Email is required.',
    invalid_firstname:"Minimun 3 character required",
    invalid_lastname:"Minimun 3 character required",
    name_required:'Name is required',
    firstname_required:'First name is required',
    lastname_required:'Last name is required',
    driving_required:'Driving Licence Number required',
    security_required:'Security Licence Number required',
    weapon_required:'Concealed Weapon Licence Number required',



    acknowledgement: "Acknowledgement",
    failed: "Failed",
    error: "Error",
    ok: "Ok",
    
    ALREADY_HAVE_AN_ACCOUNT:"Already have an account?",
    FACEBOOK_LOGIN:"Or login with facebook",
    FORGOT_PASSWORD:'Forgot password?',
    DONT_HAVE_ACCOUNT:`Don't have an account?`,
    PLEASE_ENTER_VALID: "Please enter valid ",
    PLEASE_ENTER: "Please enter ",
    PLEASE_SELECT_VALID: "Please select valid ",
    PLEASE_SELECT: "Please select ",
    INTERNET_ERROR: "Please check your internet connection",
    UNABLE_TO_PROCESS_REQUEST: "Unable to process request. Please try after some time!",
    SERVER_DOWN_ERROR: "Error : Server down! Please try again after some time!",
    UNAUTHORIZED_ERROR: "Your session has expired! Please login again!",
    PLEASE_WAIT: "Please Wait ...",
    UNABLE_TO_UPLOAD_IMAGE: "Unable to upload image. Please try after sometime",
    DATA_NOT_FOUND: "Data not found",
    LOCATION_PERMISSION_DENIED:
        "You have denied permission to access location. Please allow permissions to go ahead.",
    FETCHING_LOCATION: "Trying to find your location.. Please wait..",
    UNABLE_TO_FIND_LOCATION: "Trying to find your location.. Please wait..",
    
    USER_REGISTRATION_SUCCESS: "You have registered successfully.",
    SUBMITFLAG:'SubmitFlag',
    FETCHFLAG:'FetchFlag',
    OFFLINE_MESSAGE:' You are Offline! Please, check your internet connectivity to see submitted detail.',
    OFFLINE_MESSAGE_MOVE_IN:' You are Offline! Please, check your internet connectivity to see Move-In inspection detail.',
    SECURITY_CHECK:"For Authentication Purposes,we need your Social Security Number for background check",
    REMAIN_PRIVATE:"Remains Private - Never Shared",
    NO_CREDIT_CHECK:"No credit check - credit won't be affected ",
    INFO_SAFE:"Information is safe & secure",
    UPLOAD_FILE:" Please, upload all the relevant document applicable to you.(pdf/jpg)",
    PROCESSING_INFO:"We're Processing your information",
    PROFILE_CREATED:"En2courage Profile Created",
    SCREENING_COMPLETE:"Screening Completed , Congrats! you're approved.",
    TIME_TAKEN:"Usualy takes 1-2 days",
    PICK_SUBSCRIPTIN:"Pick subscription model",
    WORK_EARN:"Start working & earning",
    RESET_PASSWORD:"Please enter your email address.You will receive a link to reset your password.",
    SHARE_EXPERIANCE:"Please share your experience with the agent."
};

export default AppStrings;

